version: "0.1"
services:

  backend:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/code/app

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=test

    ports:
      - 5432:5432
